### ISSUE TITLE
海老ラーメンを食べに行く

### ISSUE THREAD

**Issue by comame** [LavP/ar-step#23]
いい感じのところまで作ったら、海老ラーメンを食べにいく。

**Comment by hiyakake** [comment]
@comame 
![ハイクソー](https://pbs.twimg.com/media/D2CCTwtUYAAMpW9.jpg)

**Comment by Cre-noa** [comment]
This fried chicken is delicious.
この文章を日本語に翻訳してください。


先生！質問です！
**### フライドチキンも日本語訳しますか！？**

**Comment by hiyakake** [comment]
> This fried chicken is delicious.
> この文章を日本語に翻訳してください。
> 
> 先生！質問です！
> **### フライドチキンも日本語訳しますか！？**

このissueは閉じられました。
